#!/bin/bash

status=$(cmus-remote -Q | grep status) > /dev/null 2>&1
artist=$(cmus-remote -Q | grep "tag artist" | cut -d ' ' -f 3-) > /dev/null 2>&1
track=$(cmus-remote -Q | grep title | cut -d ' ' -f 3-) > /dev/null 2>&1

if [ "$status" = "status paused" ]; then
    output="\xef\x81\x8c ${artist} - ${track}"
elif [ "$status" = 'status playing' ]; then
    output="\xef\x81\x8b ${artist} - ${track}"
fi
echo -e $output '|'
