#!/bin/sh

cmus_running=$(ps -A | grep cmus)

if [ "$cmus_running" = "" ]; then
	echo ""
	exit 1
fi

status=$(cmus-remote -Q | grep status) 

if [ "$status" = "status stopped" ]; then
	echo ""
	exit 1
elif [ "$status" = "status paused" ]; then
	statlogo="⏸"
elif [ "$status" = "status playing" ]; then
	statlogo="▶"
fi

is_stream=$(cmus-remote -Q | grep -v file | grep stream)

if [ "$(echo -e $is_stream | grep stream)" ]; then
		echo -e 📡 $(echo -e $is_stream | cut -c 8-)'|'
else
	artist=$(cmus-remote -Q | grep "tag artist" | cut -d ' ' -f 3-)
	track=$(cmus-remote -Q | grep title | cut -d ' ' -f 3-)
	tracklength=$(echo -n "$track" | wc -m)
	if [ $tracklength -gt 20 ]; then
		track=$(echo $(echo "$track" -n | cut -c -20)"... ")
	fi
	echo -e $statlogo $artist - $track'|'
fi
